# Generated by Django 4.2.5 on 2023-09-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftbill', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
