# Generated by Django 4.2.5 on 2023-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swiftbill', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAYSTACK_SECRET_KEY', models.CharField(max_length=150)),
                ('PAYSTACK_PUBLIC_KEY', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Api_config',
                'verbose_name_plural': 'Api_configs',
            },
        ),
    ]
