# Generated by Django 4.2.5 on 2023-09-08 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swiftbill', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_config',
            name='TEST_PAYSTACK_PUBLIC_KEY',
            field=models.CharField(default=111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api_config',
            name='TEST_PAYSTACK_SECRET_KEY',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
