# Generated by Django 4.2.5 on 2023-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftbill', '0004_api_config_test_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_config',
            name='PAYSTACK_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='api_config',
            name='PAYSTACK_SECRET_KEY',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='api_config',
            name='TEST_PAYSTACK_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='api_config',
            name='TEST_PAYSTACK_SECRET_KEY',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
