# Generated by Django 4.2.5 on 2023-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftbill', '0008_rename_userbalance_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default=0.0, max_length=150),
        ),
    ]
