# Generated by Django 4.2.5 on 2023-10-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftbill', '0011_rename_public_key_api_config_giftbill_public_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_config',
            old_name='GIFTBILL_PUBLIC_KEY',
            new_name='GIFTBILL_API_KEY',
        ),
        migrations.RemoveField(
            model_name='api_config',
            name='GIFTBILL_SECRET_KEY',
        ),
    ]
